assets:
  enabled: true
production:
  minify_css: true
  minify_js: true

collections_dir: _collections
collections:
  skills_en:
    output: False
    sort_by: order
  experience_en:
    output: False
    sort_by: order
  realizations_en:
    output: False
    sort_by: date
  projects_en:
    output: False
    sort_by: date
  steps_en:
    output: False
    sort_by: order
  services_en:
    output: False
    sort_by: order
  skills_pl:
    output: False
    sort_by: order
  experience_pl:
    output: False
    sort_by: order
  realizations_pl:
    output: False
    sort_by: date
  projects_pl:
    output: False
    sort_by: date
  steps_pl:
    output: False
    sort_by: order
  services_pl:
    output: False
    sort_by: order
  blog_posts:
    permalink: /en/blog/:year/:month/:day/:title/
    output: True
    sort_by: date
exclude: ['algorithm-tmpl.odt', 'README.md', 'LICENSE.txt']
